[package]
name = "forge_interpreter"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
regex = "1"
crossterm = "0.27"
anyhow = "1"
thiserror = "1"
lazy_static = "1"
serde_json = "1.0"
libloading = "0.8"

[build-dependencies]
winresource = "0.1"